import axios from "axios";
import { LOGIN, LOGOUT } from "../actions/authActionTypes";

export function loginSuccessAction(obj) {
  return {
    type: LOGIN,
    token: obj.token,
    userData: obj.userData
  };
}

export function logoutAction() {
  localStorage.clear("token"); //we clear the token in local storage
  localStorage.clear("userData"); //and userData
  return {
    type: LOGOUT
  };
}

export function loginThunk(email, password) { //the token was created when we logged in and now we need to obtain the token that was generated by using loginThunk
  localStorage.clear("token");  //
  localStorage.clear("userData");

  return dispatch => { //callback function
    console.log(email, password);
    return axios
      .post(`${process.env.REACT_APP_API_SERVER}/api/login`, {
        email: email,
        password: password
      })
      .then(response => {
        if (response.data !== null) {
          localStorage.setItem("token", response.data.token); //after axios post to login it will give you back the token here
          return  axios
            .get(`${process.env.REACT_APP_API_SERVER}/api/secret`, {
              headers: { Authorization: `Bearer ${response.data.token}` }
            });
        }
        throw new Error("Invalid login");
      })
      .then(response => {
        if (response.data !== null) {
          localStorage.setItem("userData", JSON.stringify(response.data));//after getting the token we can then get the userData

          const obj = {
            token: localStorage.getItem("token"), //token and userData will be assigned in constant obj
            userData: localStorage.getItem("userData") //we can then check line #4
          };
          dispatch(loginSuccessAction(obj)); //dispatch will now trigger reducer and perform task.. As a refresher, ACTION tells you what to do while Reducer tells you how to do it
        }
      })
      .catch(err => console.log("Error: ", err));
  };
}
